use master;
CREATE DATABASE KPROJECT_KONDRASHOVA_ALINA;

USE KPROJECT_KONDRASHOVA_ALINA;

CREATE TABLE USERS (
ID_USER NVARCHAR(25) CONSTRAINT USERS_PK PRIMARY KEY NOT NULL ,
LOGIN_USER NVARCHAR(25) NOT NULL,
PASSWORD_USER NVARCHAR(25) NOT NULL,
NAME_USER NVARCHAR(75) NOT NULL,
DATATIME_REG DATETIME NOT NULL
);

CREATE TABLE PRODUCTS(
НАЗВАНИЕ nvarchar(50) CONSTRAINT PRODUCTS_НАЗВАНИЕ_PK PRIMARY KEY  not null,
ТИП nvarchar(20) not null,
КАЛОРИЙНОСТЬ INT NOT NULL,
БЕЛКИ REAL,
ЖИРЫ REAL,
УГЛЕВОДЫ REAL,
СПИРТ REAL);

CREATE TABLE RECIPES(
RECIPE_NAME NVARCHAR(50) NOT NULL,
AUTHOR NVARCHAR(25) CONSTRAINT RECIPES_AUTHOR_FK FOREIGN KEY REFERENCES USERS(ID_USER) NOT NULL,
RECIPE_TEXT NVARCHAR(1500) NOT NULL,
NUMB_OF_SERVINGS INT CONSTRAINT NUMB_OF_SERVINGS_CHECK DEFAULT 1 CHECK(NUMB_OF_SERVINGS BETWEEN 1 AND 20),
PROD1 NVARCHAR(50) CONSTRAINT RECIPES_PROD1_FK FOREIGN KEY REFERENCES PRODUCTS(НАЗВАНИЕ) NOT NULL,
GEN_CALORIUM INT NOT NULL,
GEN_PROTEINS INT,
GEN_FAT INT,
GEN_carbohydr int,
PRIMARY KEY(RECIPE_NAME, AUTHOR)
);

INSERT INTO PRODUCTS(НАЗВАНИЕ, ТИП, КАЛОРИЙНОСТЬ, БЕЛКИ, ЖИРЫ, УГЛЕВОДЫ, СПИРТ)
VALUES ('Бренди', 'Алкоголь',255,  0,0,1,40),
('Вермут', 'Алкоголь', 155, 0 ,0 , 15.9, 15 ),
('Вино сухое', 'Алкоголь', 66,0, 0, 0, 12 );


